# Generated by Django 2.2.2 on 2019-06-15 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('file_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(max_length=20)),
                ('date_loaded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='File Load Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_data_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayAliasList',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Alias Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday Alias',
            },
        ),
        migrations.CreateModel(
            name='HolidayCountryList',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Country Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday Country',
            },
        ),
        migrations.CreateModel(
            name='HolidayOriginList',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Origin Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Holiday Origin',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('hijri_day', models.SmallIntegerField(blank=True, null=True, verbose_name='Hijri Day')),
                ('hijri_month', models.SmallIntegerField(blank=True, choices=[(1, 'Muharram'), (2, 'Safar'), (3, 'Rabi-ul-Awwal'), (4, 'Rabi-us-Sani'), (5, 'Jamadi-ul-Awwal'), (6, 'Jamadi-us-Sani'), (7, 'Rajab'), (8, 'Shaaban'), (9, 'Ramazan'), (10, 'Shawwal'), (11, 'Ziquad'), (12, 'Zilhij')], null=True, verbose_name='Hijri Month')),
                ('day', models.SmallIntegerField(blank=True, null=True, verbose_name='Gregorian Day')),
                ('month', models.SmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'Novemeber'), (12, 'December')], null=True, verbose_name='Gregorian Month')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alias_names', models.ManyToManyField(blank=True, null=True, to='hijri_calendar_app.HolidayAliasList')),
                ('country', models.ManyToManyField(blank=True, null=True, to='hijri_calendar_app.HolidayCountryList')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hijri_calendar_app.HolidayOriginList')),
            ],
            options={
                'verbose_name': 'Holiday',
            },
        ),
        migrations.CreateModel(
            name='HijriCalendar',
            fields=[
                ('date_value', models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Gregorian Date')),
                ('day', models.SmallIntegerField(verbose_name='Gregorian Day')),
                ('month', models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'Novemeber'), (12, 'December')], verbose_name='Gregorian Month')),
                ('year', models.SmallIntegerField(verbose_name='Gregorian Year')),
                ('month_name', models.CharField(default=None, editable=False, max_length=20, verbose_name='Month Label')),
                ('hijri_day', models.SmallIntegerField(verbose_name='Hijri Day')),
                ('hijri_month', models.SmallIntegerField(choices=[(1, 'Muharram'), (2, 'Safar'), (3, 'Rabi-ul-Awwal'), (4, 'Rabi-us-Sani'), (5, 'Jamadi-ul-Awwal'), (6, 'Jamadi-us-Sani'), (7, 'Rajab'), (8, 'Shaaban'), (9, 'Ramazan'), (10, 'Shawwal'), (11, 'Ziquad'), (12, 'Zilhij')], verbose_name='Hijri Month')),
                ('hijri_year', models.SmallIntegerField(verbose_name='Hijri Year')),
                ('hijri_month_name', models.CharField(default=None, editable=False, max_length=20, verbose_name='Hijri Month Name')),
                ('hijri_date_value', models.CharField(editable=False, max_length=10, verbose_name='Hijri Date')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Is Holiday')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date_entries', to='hijri_calendar_app.DataFile')),
                ('holiday_list', models.ManyToManyField(related_name='holiday_dates', to='hijri_calendar_app.Holiday')),
            ],
            options={
                'verbose_name': 'Hijri Islamic Calendar',
                'ordering': ['-date_value'],
                'get_latest_by': '-date_value',
            },
        ),
        migrations.AddIndex(
            model_name='hijricalendar',
            index=models.Index(fields=['hijri_month', 'hijri_day'], name='hijri_idx'),
        ),
        migrations.AddIndex(
            model_name='hijricalendar',
            index=models.Index(fields=['month', 'day'], name='gregorian_idx'),
        ),
        migrations.AddIndex(
            model_name='hijricalendar',
            index=models.Index(fields=['is_holiday'], name='is_holiday_idx'),
        ),
        migrations.AddConstraint(
            model_name='hijricalendar',
            constraint=models.UniqueConstraint(fields=('hijri_year', 'hijri_month', 'hijri_day'), name='unique_hijri_date'),
        ),
    ]
