# Generated by Django 2.2.1 on 2019-06-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hijricalendar',
            options={'get_latest_by': 'dateValue', 'ordering': ['-dateValue'], 'verbose_name': 'hijri islamic calendar'},
        ),
        migrations.AlterUniqueTogether(
            name='hijricalendar',
            unique_together={('lunarYear', 'lunarMonth', 'lunarDay')},
        ),
    ]
