# Generated by Django 2.2.2 on 2019-06-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_birthday',
            field=models.BooleanField(default=False, verbose_name='Is Birthday'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_cultural',
            field=models.BooleanField(default=False, verbose_name='Is Cultural'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_official',
            field=models.BooleanField(default=True, verbose_name='Is Official'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_religious',
            field=models.BooleanField(default=False, verbose_name='Is Religious'),
        ),
        migrations.CreateModel(
            name='HolidayRegionList',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Region Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hijri_calendar_app.HolidayCountryList')),
            ],
            options={
                'verbose_name': 'Holiday Region',
            },
        ),
        migrations.AddField(
            model_name='holiday',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='hijri_calendar_app.HolidayRegionList'),
        ),
    ]
