# Generated by Django 2.2.2 on 2019-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0002_auto_20190603_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='FileName',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
