# Generated by Django 2.2.2 on 2019-06-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0002_auto_20190621_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
