# Generated by Django 2.2.2 on 2019-06-28 03:30

from django.db import migrations, models
import hijri_calendar_app.models as m


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0003_auto_20190621_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='upload',
            field=models.FileField(blank=True, null=True, 
                                   upload_to=m.data_file_directory_path),
        ),
    ]
