# Generated by Django 2.2.2 on 2019-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0003_datafile_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hijricalendar',
            options={'get_latest_by': 'dateValue', 'ordering': ['-dateValue'], 'verbose_name': 'Hijri Islamic Calendar'},
        ),
        migrations.AlterField(
            model_name='hijricalendar',
            name='lunarMonth',
            field=models.SmallIntegerField(choices=[(1, 'MUHARRAM'), (2, 'Safar'), (3, 'RABI-UL-AWWAL'), (4, 'Rabi-us-Sani'), (5, 'JAMADI-UL-AWWAL'), (6, 'Jamadi-us-Sani'), (7, 'Rajab'), (8, 'Shaaban'), (9, 'Ramazan'), (10, 'Shawwal'), (11, 'Ziquad'), (12, 'Zilhij')], verbose_name='Lunar Month'),
        ),
        migrations.AlterField(
            model_name='hijricalendar',
            name='lunarYear',
            field=models.SmallIntegerField(verbose_name='Lunar Year'),
        ),
        migrations.AlterField(
            model_name='hijricalendar',
            name='month',
            field=models.SmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'Novemeber'), (12, 'December')], verbose_name='Gregorian Month'),
        ),
    ]
