# Generated by Django 2.2.2 on 2019-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hijri_calendar_app', '0004_auto_20190609_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='DateLoaded',
            field=models.DateField(default=None, verbose_name='File Load Date'),
        ),
        migrations.AddField(
            model_name='hijricalendar',
            name='lunarMonthLabel',
            field=models.CharField(default=None, max_length=20, verbose_name='Lunar Month Label'),
        ),
        migrations.AddField(
            model_name='hijricalendar',
            name='monthLabel',
            field=models.CharField(default=None, max_length=20, verbose_name='Month Label'),
        ),
    ]
