dist: xenial   # required for Python >= 3.7
language: python
services:
  - docker
python:
  - "3.7"
  # # PyPy versions
  # - "pypy3.5"
# command to install dependencies
before_install:
  - docker --version
  - docker build -t bilgrami/hijricalendar:latest .
  - docker run -d -p 127.0.0.1:80:5000 bilgrami/hijricalendar:latest /bin/sh -c "cd /opt/startup; ./init_container.sh;"
  - docker ps -a
  # - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# install:
#   - pip install -r requirements.txt
#   - pip install .
# command to run tests
script: cd ./project/hijri_calendar_project/ && python manage.py test;
