version: '3.7'

services:
  web:
    image: bilgrami/hijricalendar:latest
    volumes:
      - ${WEBAPP_STORAGE_HOME}/docker/volumes/webdata:/usr/local/project/hijri_calendar_project/data

    ports:
      - "5000:5000"
      - "8888:8888"
      - "80:2222"
      - "8080:8080"
    environment:
      - "DATABASE_ENGINE=django.db.backends.postgresql"
      - "DATABASE_NAME=postgres"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=docker"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "SECRET_KEY=!r71&*14evg0slrxi+lqkrl5uq%&-oz5:y@:6^7ck&wglssv_@;"
      - "HOST_PROJECT_FOLDER=./project/hijri_calendar_project"
      - "TARGET_PROJECT_FOLDER=/usr/local/project/hijri_calendar_project"
      - "STATIC_URL=/static/"
      - "DEBUG=True"
      - "SERVER_PORT=80"
      - "iPYTHON_NOTEBOOK_PORT=8080"
      - "PROJECT_ROOT=/usr/local/project"
      - "PROJECT_NAME=hijri_calendar_project"
      - "CONFIG_ROOT=/usr/local/project/config"
      - "VIRTUAL_ENV=/usr/local/project/.virtualenvs/myproject_env"
      - "ADMIN_USER=admin"
      - "ADMIN_PASSWD=admin!23"
      - "ADMIN_EMAIL=admin_user@email.com"
      - "SSH_PORT=2222"
      - "REDIS_HOST=redis"

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=postgres"

  redis:
    container_name: 'redis'
    image: "redis:alpine"
    ports:
      - "6579:6379"
    volumes:
      - "${WEBAPP_STORAGE_HOME}/docker/volumes/redisdata:/data"

volumes:
  postgres:
