version: '3'

services:
  db:
    image: postgres
    env_file: .env
  web:
    image: bilgrami/hijri-calendar:latest
    volumes:
      # - ./project/hijri_calendar_project:/usr/local/project/hijri_calendar_project
      - ${HOST_PROJECT_FOLDER}:${TARGET_PROJECT_FOLDER}
    ports:
      - "5000:5000"
    depends_on:
      - db
  redis:
    image: "redis:alpine"
