version: 2.0
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Getting code
          command: |
            echo '^^^ Code Files ^^^'
            ls -al
      - run:
          name: Start containers and run tests
          environment:
            IMAGE_NAME: bilgrami/hijricalendar
            version: 0.1.3
          command: |      
            set -x
            echo Product version is ${version};
            docker version # detailed version info for docker
            docker-compose version # detailed version info for docker-compose
            docker pull "$IMAGE_NAME" || true
            docker build -t ${IMAGE_NAME} .
            docker-compose up -d
            docker ps
            docker-compose exec web bash -c 'cd /usr/local/project/hijri_calendar_project && python manage.py test'
            # docker-compose exec web bash -c 'cd /usr/local/project/hijri_calendar_project && coverage run --source=. manage.py test'
