version: 2.0
jobs:
  build:
    working_directory: ~/project/hijri_calendar_project
    docker:
      - image: bilgrami/hijricalendar # primary container for the build job
    steps:
      - checkout
      - run:
          name: Getting code
          command: |
            echo '^^^ Files ^^^'
            ls -al
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.7";
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz;
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin      
      - run:
          name: Start container and verify it is working
          environment:
            IMAGE_NAME: bilgrami/hijricalendar
            version: 0.1.3
          command: |      
            set -x
            echo Product version is ${version};
            docker version # detailed version info for docker
            docker-compose version # detailed version info for docker-compose
            docker pull "$IMAGE_NAME" || true
            docker build -t ${IMAGE_NAME} .
            docker-compose up -d
            docker ps -a
            docker run -d -p 127.0.0.1:80:5000 ${IMAGE_NAME} /bin/sh -c "cd /opt/startup; ./init_container.sh;"
            cd ./project/hijri_calendar_project;
            python manage.py test;
            coverage run --source=. manage.py test
